# This is a basic workflow to help you get started with Actions

name: Multiline File CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
#       - name: post to beeceptor
#         run: |
#           curl -v -X POST 'https://ghaction.free.beeceptor.com/my/api/path' -d "${{ secrets.KEY_INLINE }}"
#           curl -v -X POST 'https://ghaction.free.beeceptor.com/my/api/path' -d ${{ toJSON(secrets.KEY_MULTILINE) }}

      - name: test 1
        if: always()
        run: |
          echo ${{ secrets.KEY_MULTILINE }}
          echo "${{ secrets.KEY_MULTILINE }}"
      
      - name: test 2
        if: always()
        run: |
          echo ${{ toJSON(secrets.KEY_MULTILINE) }}
          echo ${{ fromJSON(toJSON(secrets.KEY_MULTILINE)) }}
          
      - name: test 3
        if: always()
        run: |
          echo ${{ fromJSON(secrets.KEY_MULTILINE) }}
          echo ${{ toJSON(fromJSON(secrets.KEY_MULTILINE)) }}
