name: Test Workflow

on:
  push:
    branches: [main]

jobs:
  step1:
    runs-on: ubuntu-latest
    env:
      ARR: ${{ '("auth" "graphql" "note" "notification" "sticky" "survey")' }}
    steps:
      - run: echo $ARR
      - run: |
          ARR2=${{ env.ARR }}
          for elem in "${ARR2[@]}"; do echo $elem ; done
