name: Test Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        type: choice
        options:
          - staging
          - production
        default: staging
        required: true

jobs:
  step1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ fromJSON(format('["{0}"]', github.event.inputs.environment || 'staging')) }}
    env:
      VAR: value
      VAR2: ($VAR)
    steps:
      - name: var
        run: echo "${{ env.VAR }} | $VAR"
      - name: var2
        run: echo "${{ env.VAR2 }} | $VAR2"
