name: Test Workflow

on:
  push:
    branches: [main]

jobs:
  step1:
    runs-on: ubuntu-latest
    env:
      ARR1: ${{ '["auth","graphql","note","notification","sticky","survey"]' }}
      ARR2: ${{ fromJSON('["auth","graphql","note","notification","sticky","survey"]') }}
    steps:
      - run: echo ${{ env.ARR1 }}
      - run: echo ${{ env.ARR2 }}
      - run: echo $ARR1
      - run: echo $ARR2
