name: Test Workflow

on:
  push:
    branches: [main]

jobs:
  step1:
    runs-on: ubuntu-latest
    env:
      VAR: one
    steps:
      - id: step1
        run: echo """::set-output name:one::1.0.12"""
      - run: echo ${{ steps.step1.outputs[env.VAR] }}
