name: Test Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  step1:
    runs-on: ubuntu-latest
    env:
      VAR: value
      VAR2: ($VAR)
    steps:
      - name: var
        run: echo "${{ env.VAR }} | $VAR"
      - name: var2
        run: echo "${{ env.VAR2 }} | $VAR2"
